[versions]
atomicfu = "0.29.0" # https://maven.pkg.jetbrains.space/kotlin/p/wasm/experimental/org/jetbrains/kotlinx/atomicfu/
coroutines = "1.10.2"
serialization = "1.9.0"
ser-build-logic = "1.8.1"
datetime = "0.7.1-0.6.x-compat"
toml = "0.5.0"
html = "0.12.0"
yaml = "0.13.0"
cli = "0.3.6"
bson = "0.7.0"
coil = "3.3.0"
browser = "0.5.0"
rpc = "0.10.1"

[libraries]
cli = { module = "org.jetbrains.kotlinx:kotlinx-cli", version.ref = "cli" }

atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "coroutines" }
html = { module = "org.jetbrains.kotlinx:kotlinx-html", version.ref = "html" }

serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
serialization-build-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "ser-build-logic" }
serialization-bson = { module = "com.github.jershell:kbson", version.ref = "bson" }
serialization-yaml = { module = "net.mamoe.yamlkt:yamlkt", version.ref = "yaml" }
serialization-toml = { module = "net.peanuuutz.tomlkt:tomlkt", version.ref = "toml" }

rpc-core = { module = "org.jetbrains.kotlinx:kotlinx-rpc-core", version.ref = "rpc" }
rpc-krpc-client-core = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-client", version.ref = "rpc" }
rpc-krpc-client-ktor = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-ktor-client", version.ref = "rpc" }
rpc-krpc-server-core = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-server", version.ref = "rpc" }
rpc-krpc-server-ktor = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-ktor-server", version.ref = "rpc" }
rpc-krpc-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-rpc-krpc-serialization-json", version.ref = "rpc" }

datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "browser" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-ktor2 = { module = "io.coil-kt.coil3:coil-network-ktor2", version.ref = "coil" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

[plugins]
atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "atomicfu" }
rpc = { id = "org.jetbrains.kotlinx.rpc.plugin", version.ref = "rpc" }