[versions]
atomicfu = "0.19.0"
coroutines = "1.6.4"
serialization = "1.5.0-RC" # "1.4.1"	
datetime = "0.4.0"
ktoml = "0.4.0"
yaml = "0.12.0"
cli = "0.3.5"

[libraries]
cli = { module="org.jetbrains.kotlinx:kotlinx-cli", version.ref = "cli" }

atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
serialization-yaml = { module = "net.mamoe.yamlkt:yamlkt", version.ref = "yaml" }

serialization-toml-core = { module = "com.akuleshov7:ktoml-core", version.ref = "ktoml" }

datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }